In [1]:
import os
import pandas as pd
import numpy as np

#### En este jupyter vamos a unificar los datos de alquiler de bicicletas obtenidos de Capital Share Bikes. Cada csv pertenece a un mes distinto, y tenemos los datos para los años 2018 y 2019.

In [2]:
os.getcwd()

'/mnt/c/Users/chloe/Documents/CURSOS/ADALAB GRAL/ADALAB/PROYECTOS/project-DA-promo-B-module-3-team-3/EDA-NUEVO-DATA'

In [4]:
os.chdir('../Datos/4. nuevo_data_trips/2019')

In [5]:
# Los arichivos a unificar
archivos = os.listdir()
archivos

['201901-capitalbikeshare-tripdata.csv',
 '201902-capitalbikeshare-tripdata.csv',
 '201903-capitalbikeshare-tripdata.csv',
 '201904-capitalbikeshare-tripdata.csv',
 '201905-capitalbikeshare-tripdata.csv',
 '201906-capitalbikeshare-tripdata.csv',
 '201907-capitalbikeshare-tripdata.csv',
 '201908-capitalbikeshare-tripdata.csv',
 '201909-capitalbikeshare-tripdata.csv',
 '201910-capitalbikeshare-tripdata.csv',
 '201911-capitalbikeshare-tripdata.csv',
 '201912-capitalbikeshare-tripdata.csv']

In [6]:
# Diccionario vacío para ir apendeando los csv en dataframes
fechas_dict = {}

In [7]:
# Prueba para insertar dataframes
fechas_dict[archivos[0]] = pd.read_csv(archivos[0], index_col=0)
fechas_dict[archivos[0]]

,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
Duration,,,,,,,,
230,2019-01-01 00:04:48,2019-01-01 00:08:39,31203,14th & Rhode Island Ave NW,31200,Massachusetts Ave & Dupont Circle NW,E00141,Member
1549,2019-01-01 00:06:37,2019-01-01 00:32:27,31321,15th St & Constitution Ave NW,31114,18th St & Wyoming Ave NW,W24067,Casual
177,2019-01-01 00:08:46,2019-01-01 00:11:44,31104,Adams Mill & Columbia Rd NW,31323,Woodley Park Metro / Calvert St & Connecticut ...,W22654,Casual
228,2019-01-01 00:08:47,2019-01-01 00:12:35,31281,8th & O St NW,31280,11th & S St NW,W22336,Member
1300,2019-01-01 00:12:29,2019-01-01 00:34:10,31014,Lynn & 19th St North,31923,Columbia Pike & S Taylor St,70004,Member
...,...,...,...,...,...,...,...,...
1070,2019-01-31 23:47:11,2019-02-01 00:05:02,31268,12th & U St NW,31618,4th & East Capitol St NE,W21008,Member
180,2019-01-31 23:52:07,2019-01-31 23:55:08,31603,1st & M St NE,31616,3rd & H St NE,W23095,Member
732,2019-01-31 23:58:33,2019-02-01 00:10:45,31638,1st & H St NW,31214,17th & Corcoran St NW,W21341,Member
688,2019-01-31 23:58:52,2019-02-01 00:10:21,31114,18th St & Wyoming Ave NW,31128,23rd & M St NW,W22170,Member
681,2019-01-31 23:58:54,2019-02-01 00:10:15,31114,18th St & Wyoming Ave NW,31128,23rd & M St NW,E00128,Member

In [8]:
# Inserción de dataframes
for i in archivos:
    fechas_dict[i] = pd.read_csv(i, index_col=0)

In [9]:
# Deberiamos tener tantos items en el diccionario como csvs a unir
len(archivos) == len(fechas_dict)

True

In [10]:
# Extraemos los dataframes a una lista
df_list = [ v for k,v in fechas_dict.items()] 
df_list

[                   Start date             End date  Start station number  \
 Duration
 230       2019-01-01 00:04:48  2019-01-01 00:08:39                 31203
 1549      2019-01-01 00:06:37  2019-01-01 00:32:27                 31321
 177       2019-01-01 00:08:46  2019-01-01 00:11:44                 31104
 228       2019-01-01 00:08:47  2019-01-01 00:12:35                 31281
 1300      2019-01-01 00:12:29  2019-01-01 00:34:10                 31014
 ...                       ...                  ...                   ...
 1070      2019-01-31 23:47:11  2019-02-01 00:05:02                 31268
 180       2019-01-31 23:52:07  2019-01-31 23:55:08                 31603
 732       2019-01-31 23:58:33  2019-02-01 00:10:45                 31638
 688       2019-01-31 23:58:52  2019-02-01 00:10:21                 31114
 681       2019-01-31 23:58:54  2019-02-01 00:10:15                 31114

                           Start station  End station number  \
 Duration
 230          14th & Rhode Island Ave NW               31200
 1549      15th St & Constitution Ave NW               31114
 177         Adams Mill & Columbia Rd NW               31323
 228                       8th & O St NW               31280
 1300               Lynn & 19th St North               31923
 ...                                 ...                 ...
 1070                     12th & U St NW               31618
 180                       1st & M St NE               31616
 732                       1st & H St NW               31214
 688            18th St & Wyoming Ave NW               31128
 681            18th St & Wyoming Ave NW               31128

                                                 End station Bike number  \
 Duration
 230                    Massachusetts Ave & Dupont Circle NW      E00141
 1549                               18th St & Wyoming Ave NW      W24067
 177       Woodley Park Metro / Calvert St & Connecticut ...      W22654
 228                                          11th & S St NW      W22336
 1300                            Columbia Pike & S Taylor St       70004
 ...                                                     ...         ...
 1070                               4th & East Capitol St NE      W21008
 180                                           3rd & H St NE      W23095
 732                                   17th & Corcoran St NW      W21341
 688                                          23rd & M St NW      W22170
 681                                          23rd & M St NW      E00128

          Member type
 Duration
 230           Member
 1549          Casual
 177           Casual
 228           Member
 1300          Member
 ...              ...
 1070          Member
 180           Member
 732           Member
 688           Member
 681           Member

 [150780 rows x 8 columns],
                    Start date             End date  Start station number  \
 Duration
 206       2019-02-01 00:00:20  2019-02-01 00:03:47                 31509
 297       2019-02-01 00:04:40  2019-02-01 00:09:38                 31203
 165       2019-02-01 00:06:34  2019-02-01 00:09:20                 31303
 176       2019-02-01 00:06:49  2019-02-01 00:09:45                 31400
 105       2019-02-01 00:10:41  2019-02-01 00:12:27                 31270
 ...                       ...                  ...                   ...
 886       2019-02-28 23:55:21  2019-03-01 00:10:08                 31223
 404       2019-02-28 23:57:03  2019-03-01 00:03:47                 31203
 972       2019-02-28 23:57:03  2019-03-01 00:13:16                 31101
 925       2019-02-28 23:57:32  2019-03-01 00:12:58                 31613
 773       2019-02-28 23:59:15  2019-03-01 00:12:08                 31255

                                               Start station  \
 Duration
 206                                New Jersey Ave & R St NW
 297                              14th & Rhode Island Ave NW
 165            Tenleytown / Wisconsin Ave & Albemarle St NW
 176                          Georgia & New Hampshire Ave NW
 105                                           8th & D St NW
 ...                                                     ...
 886                       Convention Center / 7th & M St NW
 404                              14th & Rhode Island Ave NW
 972                                          14th & V St NW
 925       Eastern Market Metro / Pennsylvania Ave & 7th ...
 773                                          24th & N St NW

           End station number                         End station Bike number  \
 Duration
 206                    31636  New Jersey Ave & N St NW/Dunbar HS      W21713
 297                    31519                       1st & O St NW      E00013
 165                    31308                 39th & Veazey St NW      W21703
 176                    31401              14th St & Spring Rd NW      W21699
 105                    31256                      10th & E St NW      W21710
 ...                      ...                                 ...         ...
 886                    31612              D St & Maryland Ave NE      W23129
 404                    31223   Convention Center / 7th & M St NW      W00316
 972                    31600                       5th & K St NW      W21796
 925                    31642            New Jersey Ave & L St NW      W23576
 773                    31233    17th & K St NW / Farragut Square      W22068

          Member type
 Duration
 206           Member
 297           Member
 165           Member
 176           Member
 105           Member
 ...              ...
 886           Member
 404           Member
 972           Member
 925           Member
 773           Member

 [158130 rows x 8 columns],
                    Start date             End date  Start station number  \
 Duration
 896       2019-03-01 00:02:23  2019-03-01 00:17:19                 31234
 613       2019-03-01 00:03:10  2019-03-01 00:13:23                 31323
 652       2019-03-01 00:04:14  2019-03-01 00:15:06                 31651
 676       2019-03-01 00:05:11  2019-03-01 00:16:27                 31400
 587       2019-03-01 00:08:04  2019-03-01 00:17:51                 31293
 ...                       ...                  ...                   ...
 159       2019-03-31 23:48:43  2019-03-31 23:51:23                 31202
 379       2019-03-31 23:49:26  2019-03-31 23:55:45                 31127
 374       2019-03-31 23:52:26  2019-03-31 23:58:41                 31119
 734       2019-03-31 23:54:33  2019-04-01 00:06:47                 31267
 742       2019-03-31 23:54:36  2019-04-01 00:06:59                 31267

                                               Start station  \
 Duration
 896                           20th & O St NW / Dupont South
 613       Woodley Park Metro / Calvert St & Connecticut ...
 652                                       11th & Park Rd NW
 676                          Georgia & New Hampshire Ave NW
 587                                      31st & Water St NW
 ...                                                     ...
 159                                          14th & R St NW
 379                                          22nd & H St NW
 374                                    14th & Belmont St NW
 734                          17th St & Massachusetts Ave NW
 742                          17th St & Massachusetts Ave NW

           End station number  \
 Duration
 896                    31306
 613                    31214
 652                    31506
 676                    31212
 587                    31250
 ...                      ...
 159                    31101
 379                    31225
 374                    31110
 734                    31523
 742                    31523

                                                 End station Bike number  \
 Duration
 896                         39th & Calvert St NW / Stoddert      W01259
 613                                   17th & Corcoran St NW      W22263
 652                               1st & Rhode Island Ave NW      W00825
 676                                          21st & M St NW      W24162
 587                                          20th & L St NW      W21644
 ...                                                     ...         ...
 159                                          14th & U St NW      W00684
 379                          C & O Canal & Wisconsin Ave NW      W21832
 374                                20th St & Florida Ave NW      W20398
 734       Lincoln Rd & Seaton Pl NE/Harry Thomas Rec Center      W23834
 742       Lincoln Rd & Seaton Pl NE/Harry Thomas Rec Center      W00818

          Member type
 Duration
 896           Member
 613           Member
 652           Member
 676           Member
 587           Member
 ...              ...
 159           Member
 379           Member
 374           Member
 734           Member
 742           Member

 [253811 rows x 8 columns],
                    Start date             End date  Start station number  \
 Duration
 313       2019-04-01 00:03:03  2019-04-01 00:08:16                 31618
 453       2019-04-01 00:07:37  2019-04-01 00:15:10                 31119
 333       2019-04-01 00:09:31  2019-04-01 00:15:05                 31203
 568       2019-04-01 00:10:20  2019-04-01 00:19:49                 31202
 1609      2019-04-01 00:10:38  2019-04-01 00:37:28                 31517
 ...                       ...                  ...                   ...
 1217      2019-04-30 23:54:03  2019-05-01 00:14:20                 31634
 1662      2019-04-30 23:55:16  2019-05-01 00:22:59                 31600
 1262      2019-04-30 23:55:56  2019-05-01 00:16:58                 31234
 453       2019-04-30 23:57:15  2019-05-01 00:04:48                 31245
 81        2019-04-30 23:58:29  2019-04-30 23:59:51                 31023

                           Start station  End station number  \
 Duration
 313            4th & East Capitol St NE               31630
 453                14th & Belmont St NW               31298
 333          14th & Rhode Island Ave NW               31519
 568                      14th & R St NW               31103
 1609                       Union Market               31655
 ...                                 ...                 ...
 1217                 3rd & Tingey St SE               31601
 1662                      5th & K St NW               31703
 1262      20th & O St NW / Dupont South               31400
 453        7th & R St NW / Shaw Library               31229
 81             Fairfax Dr & Wilson Blvd               31040

                              End station Bike number Member type
 Duration
 313            15th & East Capitol St NE      W24063      Member
 453                       15th & M St NW      W22080      Member
 333                        1st & O St NW      W00276      Member
 568                 16th & Harvard St NW      W21582      Member
 1609            New Jersey Ave & F St NW       75558      Member
 ...                                  ...         ...         ...
 1217           19th & East Capitol St SE      W23326      Casual
 1662            Minnesota Ave Metro/DOES      W24114      Member
 1262      Georgia & New Hampshire Ave NW      W23071      Member
 453          New Hampshire Ave & T St NW      W23786      Member
 81         GMU / Fairfax Dr & Kenmore St      W20818      Member

 [347992 rows x 8 columns],
                    Start date             End date  Start station number  \
 Duration
 653       2019-05-01 00:00:02  2019-05-01 00:10:55                 31127
 297       2019-05-01 00:00:13  2019-05-01 00:05:11                 31641
 129       2019-05-01 00:00:36  2019-05-01 00:02:46                 31255
 1119      2019-05-01 00:01:08  2019-05-01 00:19:48                 31655
 533       2019-05-01 00:01:20  2019-05-01 00:10:13                 31203
 ...                       ...                  ...                   ...
 434       2019-05-31 23:59:15  2019-06-01 00:06:30                 31281
 227       2019-05-31 23:59:45  2019-06-01 00:03:32                 31201
 1638      2019-05-31 23:59:45  2019-06-01 00:27:03                 31261
 1621      2019-05-31 23:59:51  2019-06-01 00:26:53                 31261
 373       2019-05-31 23:59:51  2019-06-01 00:06:04                 31281

                           Start station  End station number  \
 Duration
 653                      22nd & H St NW               31202
 297       2nd St & Massachusetts Ave NE               31603
 129                      24th & N St NW               31237
 1119           New Jersey Ave & F St NW               31244
 533          14th & Rhode Island Ave NW               31223
 ...                                 ...                 ...
 434                       8th & O St NW               31627
 227                      15th & P St NW               31229
 1638      21st St & Constitution Ave NW               31247
 1621      21st St & Constitution Ave NW               31247
 373                       8th & O St NW               31201

                                 End station Bike number Member type
 Duration
 653                          14th & R St NW      W00233      Member
 297                           1st & M St NE      W00555      Member
 129           25th St & Pennsylvania Ave NW      W23383      Member
 1119                          4th & E St SW      W20337      Member
 533       Convention Center / 7th & M St NW      W23707      Member
 ...                                     ...         ...         ...
 434                           3rd & M St NE      W23767      Member
 227             New Hampshire Ave & T St NW      W23691      Member
 1638              Jefferson Dr & 14th St SW      W20810      Member
 1621              Jefferson Dr & 14th St SW      W21714      Casual
 373                          15th & P St NW      W21769      Member

 [337704 rows x 8 columns],
                    Start date             End date  Start station number  \
 Duration
 839       2019-06-01 00:00:04  2019-06-01 00:14:03                 31245
 389       2019-06-01 00:00:13  2019-06-01 00:06:43                 31639
 270       2019-06-01 00:00:15  2019-06-01 00:04:46                 31228
 1029      2019-06-01 00:00:32  2019-06-01 00:17:41                 31251
 892       2019-06-01 00:00:33  2019-06-01 00:15:25                 31082
 ...                       ...                  ...                   ...
 733       2019-06-30 23:57:17  2019-07-01 00:09:30                 31609
 5127      2019-06-30 23:58:11  2019-07-01 01:23:39                 31292
 5145      2019-06-30 23:58:24  2019-07-01 01:24:10                 31292
 331       2019-06-30 23:59:08  2019-07-01 00:04:39                 31610
 467       2019-06-30 23:59:17  2019-07-01 00:07:05                 31319

                                          Start station  End station number  \
 Duration
 839                       7th & R St NW / Shaw Library               31508
 389                                      2nd & G St NE               31647
 270                                      8th & H St NW               31266
 1029                                    12th & L St NW               31508
 892                      Eisenhower Ave & Mill Race Ln               31088
 ...                                                ...                 ...
 733                              Maine Ave & 7th St SW               31610
 5127                     22nd St & Constitution Ave NW               31261
 5145                     22nd St & Constitution Ave NW               31261
 331       Eastern Market / 7th & North Carolina Ave SE               31612
 467                   Wisconsin Ave & Brandywine St NW               32014

                                                 End station Bike number  \
 Duration
 839                     Gallaudet / 8th St & Florida Ave NE      W23489
 389                           7th St & Massachusetts Ave NE      W00660
 270                                          11th & M St NW      W01010
 1029                    Gallaudet / 8th St & Florida Ave NE      W01313
 892                           Mount Vernon Ave & Kennedy St      W00623
 ...                                                     ...         ...
 733            Eastern Market / 7th & North Carolina Ave SE      W22399
 5127                          21st St & Constitution Ave NW      W20536
 5145                          21st St & Constitution Ave NW      W20531
 331                                  D St & Maryland Ave NE      W00795
 467       Friendship Hts Metro / Wisconsin Ave & Wiscons...      W23253

          Member type
 Duration
 839           Member
 389           Member
 270           Member
 1029          Member
 892           Member
 ...              ...
 733           Casual
 5127          Casual
 5145          Casual
 331           Member
 467           Casual

 [350144 rows x 8 columns],
                    Start date             End date  Start station number  \
 Duration
 528       2019-07-01 00:00:05  2019-07-01 00:08:53                 31312
 548       2019-07-01 00:00:17  2019-07-01 00:09:26                 31321
 1612      2019-07-01 00:00:23  2019-07-01 00:27:16                 31211
 534       2019-07-01 00:00:36  2019-07-01 00:09:30                 31321
 530       2019-07-01 00:00:52  2019-07-01 00:09:43                 31201
 ...                       ...                  ...                   ...
 1596      2019-07-31 23:55:36  2019-08-01 00:22:12                 31249
 588       2019-07-31 23:56:09  2019-08-01 00:05:58                 31104
 737       2019-07-31 23:57:44  2019-08-01 00:10:01                 31115
 359       2019-07-31 23:57:47  2019-08-01 00:03:46                 31117
 513       2019-07-31 23:59:55  2019-08-01 00:08:29                 31516

                           Start station  End station number  \
 Duration
 528             Wisconsin Ave & O St NW               31234
 548       15th St & Constitution Ave NW               31270
 1612                     Kennedy Center               31289
 534       15th St & Constitution Ave NW               31270
 530                      15th & P St NW               31109
 ...                                 ...                 ...
 1596                 Jefferson Memorial               31290
 588         Adams Mill & Columbia Rd NW               31128
 737        Columbia Rd & Georgia Ave NW               31267
 359                15th & Euclid St  NW               31282
 513              Rhode Island Ave Metro               31510

                                           End station Bike number Member type
 Duration
 528                     20th & O St NW / Dupont South      W23055      Member
 548                                     8th & D St NW      W20124      Member
 1612      Henry Bacon Dr & Lincoln Memorial Circle NW      W00461      Member
 534                                     8th & D St NW      W23106      Member
 530                                     7th & T St NW      W22710      Casual
 ...                                               ...         ...         ...
 1596                    17th St & Independence Ave SW       78598      Member
 588                                    23rd & M St NW      W24040      Member
 737                    17th St & Massachusetts Ave NW      W23142      Member
 359                                    16th & R St NW      W22184      Member
 513                     18th St & Rhode Island Ave NE      W22855      Member

 [356645 rows x 8 columns],
                    Start date             End date  Start station number  \
 Duration
 357       2019-08-01 00:00:34  2019-08-01 00:06:31                 31117
 1100      2019-08-01 00:01:48  2019-08-01 00:20:09                 31407
 1406      2019-08-01 00:04:04  2019-08-01 00:27:31                 31407
 3667      2019-08-01 00:05:09  2019-08-01 01:06:16                 31907

In [11]:
# Concatenamos los df para unificar la información
trips_info = pd.concat(df_list, axis=0)

In [12]:
trips_info.head(5)

,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
Duration,,,,,,,,
230,2019-01-01 00:04:48,2019-01-01 00:08:39,31203,14th & Rhode Island Ave NW,31200,Massachusetts Ave & Dupont Circle NW,E00141,Member
1549,2019-01-01 00:06:37,2019-01-01 00:32:27,31321,15th St & Constitution Ave NW,31114,18th St & Wyoming Ave NW,W24067,Casual
177,2019-01-01 00:08:46,2019-01-01 00:11:44,31104,Adams Mill & Columbia Rd NW,31323,Woodley Park Metro / Calvert St & Connecticut ...,W22654,Casual
228,2019-01-01 00:08:47,2019-01-01 00:12:35,31281,8th & O St NW,31280,11th & S St NW,W22336,Member
1300,2019-01-01 00:12:29,2019-01-01 00:34:10,31014,Lynn & 19th St North,31923,Columbia Pike & S Taylor St,70004,Member

In [13]:
# Vemos si tiene sentido el tamaño del nuevo dataframe
trips_info.shape

(3398417, 8)

In [14]:
# Reseteamos el índice
trips_info.reset_index(inplace=True)

In [24]:
trips_info.head()

,Duration,Start date,End date,Start station number,Start station,End station number,End station,Bike number,Member type
0,552,2018-01-01 00:05:06,2018-01-01 00:14:18,31104,Adams Mill & Columbia Rd NW,31400,Georgia & New Hampshire Ave NW,W00886,Member
1,1282,2018-01-01 00:14:30,2018-01-01 00:35:53,31321,15th St & Constitution Ave NW,31321,15th St & Constitution Ave NW,W01435,Casual
2,1265,2018-01-01 00:14:53,2018-01-01 00:35:58,31321,15th St & Constitution Ave NW,31321,15th St & Constitution Ave NW,W21242,Casual
3,578,2018-01-01 00:15:31,2018-01-01 00:25:09,31406,14th & Upshur St NW,31103,16th & Harvard St NW,W21322,Casual
4,372,2018-01-01 00:18:02,2018-01-01 00:24:15,31618,4th & East Capitol St NE,31619,Lincoln Park / 13th & East Capitol St NE,W00119,Member

In [15]:
# Guardamos a csv
trips_info.to_csv('../trips_bikes2019.csv')

#### Extracción del json stations_information a csv

In [16]:
station_info = pd.read_json('../station_information.json')
station_info

                                                       data  last_updated  ttl
stations  [{'short_name': '31000', 'legacy_id': '1', 'st...    1665508146    5

In [17]:
station_info2 = station_info['data'].apply(pd.Series)
station_info2.reset_index(inplace=True, drop=True)
station_info2.head()

,0,1,2,3,4,5,6,7,8,9,...,687,688,689,690,691,692,693,694,695,696
0,"{'short_name': '31000', 'legacy_id': '1', 'sta...","{'short_name': '31002', 'legacy_id': '3', 'sta...","{'short_name': '31003', 'legacy_id': '4', 'sta...","{'short_name': '31004', 'legacy_id': '5', 'sta...","{'short_name': '31005', 'legacy_id': '6', 'sta...","{'short_name': '31006', 'legacy_id': '7', 'sta...","{'short_name': '31007', 'legacy_id': '8', 'sta...","{'short_name': '31009', 'legacy_id': '10', 'st...","{'short_name': '31010', 'legacy_id': '11', 'st...","{'short_name': '31011', 'legacy_id': '12', 'st...",...,"{'short_name': '31136', 'legacy_id': '742', 's...","{'short_name': '31676', 'legacy_id': '743', 's...","{'short_name': '31424', 'legacy_id': '744', 's...","{'short_name': '31974', 'legacy_id': '745', 's...","{'short_name': '31137', 'legacy_id': '746', 's...","{'short_name': '31828', 'legacy_id': '747', 's...","{'short_name': '31721', 'legacy_id': '748', 's...","{'short_name': '31138', 'legacy_id': '749', 's...","{'short_name': '31536', 'legacy_id': '750', 's...","{'short_name': '31976', 'legacy_id': '751', 's..."

In [18]:
stations = station_info2.T
stations

                                                     0
0    {'short_name': '31000', 'legacy_id': '1', 'sta...
1    {'short_name': '31002', 'legacy_id': '3', 'sta...
2    {'short_name': '31003', 'legacy_id': '4', 'sta...
3    {'short_name': '31004', 'legacy_id': '5', 'sta...
4    {'short_name': '31005', 'legacy_id': '6', 'sta...
..                                                 ...
692  {'short_name': '31828', 'legacy_id': '747', 's...
693  {'short_name': '31721', 'legacy_id': '748', 's...
694  {'short_name': '31138', 'legacy_id': '749', 's...
695  {'short_name': '31536', 'legacy_id': '750', 's...
696  {'short_name': '31976', 'legacy_id': '751', 's...

[697 rows x 1 columns]

In [19]:
stations = stations[0].apply(pd.Series)
stations.head()

,short_name,legacy_id,station_type,capacity,name,region_id,external_id,lat,lon,eightd_station_services,eightd_has_key_dispenser,station_id,rental_uris,rental_methods,has_kiosk,electric_bike_surcharge_waiver
0,31000,1,classic,15,Eads St & 15th St S,41,082469cc-1f3f-11e7-bf6b-3863bb334450,38.858971,-77.053230,[],False,1,{'android': 'https://dc.lft.to/lastmile_qr_sca...,"[CREDITCARD, KEY]",True,False
1,31002,3,classic,17,Crystal Dr & 20th St S,41,08246c35-1f3f-11e7-bf6b-3863bb334450,38.856425,-77.049232,[],False,3,{'android': 'https://dc.lft.to/lastmile_qr_sca...,"[CREDITCARD, KEY]",True,False
2,31003,4,classic,16,Crystal Dr & 15th St S,41,08246cd5-1f3f-11e7-bf6b-3863bb334450,38.861056,-77.049417,[],False,4,{'android': 'https://dc.lft.to/lastmile_qr_sca...,"[CREDITCARD, KEY]",True,False
3,31004,5,classic,12,Aurora Hills Cmty Ctr / 18th St & S Hayes St,41,08246d68-1f3f-11e7-bf6b-3863bb334450,38.857866,-77.059490,[],False,5,{'android': 'https://dc.lft.to/lastmile_qr_sca...,"[CREDITCARD, KEY]",True,False
4,31005,6,classic,19,Pentagon City Metro / 12th St & S Hayes St,41,08246df5-1f3f-11e7-bf6b-3863bb334450,38.862303,-77.059936,[],False,6,{'android': 'https://dc.lft.to/lastmile_qr_sca...,"[CREDITCARD, KEY]",True,False

In [20]:
# Nos quedamos únicamente con las columnas que nos interesan
stations= stations[['short_name', 'capacity', 'name', 'region_id', 'lat', 'lon']]
stations

,short_name,capacity,name,region_id,lat,lon
0,31000,15,Eads St & 15th St S,41,38.858971,-77.053230
1,31002,17,Crystal Dr & 20th St S,41,38.856425,-77.049232
2,31003,16,Crystal Dr & 15th St S,41,38.861056,-77.049417
3,31004,12,Aurora Hills Cmty Ctr / 18th St & S Hayes St,41,38.857866,-77.059490
4,31005,19,Pentagon City Metro / 12th St & S Hayes St,41,38.862303,-77.059936
...,...,...,...,...,...,...
692,31828,19,New Jersey Ave & H St SE,NaN,38.880761,-77.005741
693,31721,19,Anacostia Ave & East Capitol St NE,NaN,38.890461,-76.961280
694,31138,15,4th & College St NW,NaN,38.921233,-77.018135
695,31536,19,5th & Morse St NE,42,38.907287,-76.999167
696,31976,15,Virginia Hospital Center,41,38.887914,-77.128015

In [21]:
# Guardamos como csv
stations.to_csv('../stations_info.csv')

#### Realizamos un breve análisis exploratorio de estos datos

In [22]:
# Vemos que las estaciones pertenecen a varias regiones, de las cuales nos interesa Washington DC, la 42
stations.region_id.value_counts()

42     345
41     108
40      60
44      56
104     54
43      31
133     27
152     10
Name: region_id, dtype: int64

In [23]:
stations.region_id.isnull().sum()

6